name: Dom Sherlock
favicon: null
layout_spectrum: 0.23458
typography_spectrum: 0.7387744269799441
title: This could be the greatest thing on the internet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
